name: master_gelo
description: "!!!"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0' # Recomendação de ajuste para maior compatibilidade

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  intl: ^0.19.0
  fl_chart: ^0.68.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  url_launcher: ^6.2.5
  package_info_plus: ^8.0.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.9
  shared_preferences: ^2.2.3
  pdf: ^3.10.8
  printing: ^5.12.0
  mercadopago_sdk: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/cubo-de-gelo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/backgrounds/