// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6EruzCKqVAUcJbEQKMCHCs_fIgvX17FQ',
    appId: '1:527743404730:web:002a762d67eb4b32999083',
    messagingSenderId: '527743404730',
    projectId: 'gelo-gestor',
    authDomain: 'gelo-gestor.firebaseapp.com',
    storageBucket: 'gelo-gestor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwUcOG3AauevpximLGMZK7r_j48_IBzE4',
    appId: '1:527743404730:android:145db77c98420e35999083',
    messagingSenderId: '527743404730',
    projectId: 'gelo-gestor',
    storageBucket: 'gelo-gestor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3TGjJAVTLWLig0qRoqAb9ur7ymyOSdGs',
    appId: '1:527743404730:ios:50c0bb530cc9c591999083',
    messagingSenderId: '527743404730',
    projectId: 'gelo-gestor',
    storageBucket: 'gelo-gestor.firebasestorage.app',
    iosBundleId: 'com.rodrigocostadev.tiendaModel',
  );
}
